import { CensusRecord } from './types';

export const COMMON_TRIBES = [
  'Dinka (Jieng)',
  'Nuer (Naath)',
  'Bari',
  'Azande',
  'Shilluk (Chollo)',
  'Anyuak',
  'Acholi',
  'Madi',
  'Lotuko (Otuho)',
  'Toposa',
  'Fertit',
  'Kakwa',
  'Murle',
  'Mundari',
  'Luo',
  'Kuku',
  'Yoruba',
  'Hausa',
  'Igbo',
  'Oromo',
  'Amhara',
  'Kikuyu',
  'Maasai',
  'Zulu',
  'Xhosa',
  'Other / Not Listed'
];

export const COMMON_REGIONS = [
  'Central Equatoria',
  'Eastern Equatoria',
  'Western Equatoria',
  'Jonglei',
  'Unity State',
  'Upper Nile',
  'Lakes State',
  'Warrap',
  'Western Bahr el Ghazal',
  'Northern Bahr el Ghazal',
  'Nairobi Metropolitan',
  'Addis Ababa Capital',
  'Lagos State',
  'Greater Accra',
  'Kampala Central'
];

export const COMMON_COMMUNITIES = [
  'Munuki Residential Area',
  'Gudele Community',
  'Kator Parish Ward',
  'Malakal Central Settlement',
  'Bor Town Zone 3',
  'Rumbek Palm Grove',
  'Yambio Green Valley',
  'Torit Hillside Community',
  'Aweil Railway District',
  'Bentiu Riverside Block',
  'Kapoeta Goldfield Boma',
  'Nimule Border Township',
  'Wau Old Town',
  'Juba Na Bari Sector',
  'Kuajok Civic Center'
];

export const COMMON_LANGUAGES = [
  'Dinka (Thuɔŋjäŋ)',
  'Nuer (Thok Nath)',
  'Bari',
  'Zande',
  'Shilluk (Dhok Chollo)',
  'Arabic (Juba Arabic)',
  'English',
  'Swahili',
  'Acholi',
  'Lotuko',
  'Toposa',
  'Amharic',
  'Yoruba',
  'Hausa',
  'Igbo',
  'French',
  'Other'
];

export const INITIAL_CENSUS_RECORDS: CensusRecord[] = [
  {
    id: 'CEN-2026-0101',
    nationalId: 'SS-98214301-A',
    fullName: 'Deng Majok Akech',
    age: 48,
    dateOfBirth: '1978-04-12',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Rek / Aguok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Munuki Residential Area',
    subCountyOrBoma: 'Munuki Block B',
    countyOrPayam: 'Juba Payam',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Plot 142, Street 8, Munuki',
    durationOfStayYears: 14,
    householdId: 'HH-001',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Public/Civil Service)',
    primaryOccupation: 'Senior Education Officer',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-15',
    verificationStatus: 'Verified',
    notes: 'Household registered during morning field route. Physical verification complete.',
    createdAt: '2026-08-15T08:30:00Z',
    updatedAt: '2026-08-15T08:30:00Z'
  },
  {
    id: 'CEN-2026-0102',
    nationalId: 'SS-98214302-B',
    fullName: 'Achan Mary Chol',
    age: 42,
    dateOfBirth: '1984-09-20',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Rek / Aguok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Munuki Residential Area',
    subCountyOrBoma: 'Munuki Block B',
    countyOrPayam: 'Juba Payam',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Plot 142, Street 8, Munuki',
    durationOfStayYears: 14,
    householdId: 'HH-001',
    householdRole: 'Spouse',
    isHouseholdHead: false,
    educationLevel: 'Vocational / Diploma',
    isLiterate: true,
    employmentStatus: 'Self-Employed / Business',
    primaryOccupation: 'Wholesale Grain Merchant',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-15',
    verificationStatus: 'Verified',
    createdAt: '2026-08-15T08:45:00Z',
    updatedAt: '2026-08-15T08:45:00Z'
  },
  {
    id: 'CEN-2026-0103',
    fullName: 'Santino Dut Deng',
    age: 18,
    dateOfBirth: '2008-01-14',
    gender: 'Male',
    maritalStatus: 'Single',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Rek / Aguok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Munuki Residential Area',
    subCountyOrBoma: 'Munuki Block B',
    countyOrPayam: 'Juba Payam',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Plot 142, Street 8, Munuki',
    durationOfStayYears: 14,
    householdId: 'HH-001',
    householdRole: 'Son / Daughter',
    isHouseholdHead: false,
    educationLevel: 'Secondary Education',
    isLiterate: true,
    employmentStatus: 'Student',
    primaryOccupation: 'Secondary Student - Science',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-15',
    verificationStatus: 'Verified',
    createdAt: '2026-08-15T08:55:00Z',
    updatedAt: '2026-08-15T08:55:00Z'
  },
  {
    id: 'CEN-2026-0104',
    fullName: 'Nyibol Grace Deng',
    age: 12,
    dateOfBirth: '2014-06-03',
    gender: 'Female',
    maritalStatus: 'Single',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Rek / Aguok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Munuki Residential Area',
    subCountyOrBoma: 'Munuki Block B',
    countyOrPayam: 'Juba Payam',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Plot 142, Street 8, Munuki',
    durationOfStayYears: 12,
    householdId: 'HH-001',
    householdRole: 'Son / Daughter',
    isHouseholdHead: false,
    educationLevel: 'Primary Education',
    isLiterate: true,
    employmentStatus: 'Student',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-15',
    verificationStatus: 'Verified',
    createdAt: '2026-08-15T09:05:00Z',
    updatedAt: '2026-08-15T09:05:00Z'
  },
  {
    id: 'CEN-2026-0201',
    nationalId: 'SS-44719023-F',
    fullName: 'Gatluak Ruai Kuol',
    age: 39,
    dateOfBirth: '1987-11-15',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Nuer (Naath)',
    subTribeOrClan: 'Lou Nuer / Mor',
    nativeLanguage: 'Nuer (Thok Nath)',
    nationality: 'South Sudan',
    community: 'Bentiu Riverside Block',
    subCountyOrBoma: 'Rubkona North Boma',
    countyOrPayam: 'Rubkona County',
    stateOrRegion: 'Unity State',
    residentialAddress: 'Sector 4, Riverside Bend',
    durationOfStayYears: 8,
    householdId: 'HH-002',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Private Sector)',
    primaryOccupation: 'Community Health Coordinator',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Peter Gatwich Koang',
    enumeratorBadgeId: 'ENUM-088',
    enumerationDate: '2026-08-16',
    verificationStatus: 'Verified',
    createdAt: '2026-08-16T10:15:00Z',
    updatedAt: '2026-08-16T10:15:00Z'
  },
  {
    id: 'CEN-2026-0202',
    nationalId: 'SS-44719024-G',
    fullName: 'Nyadak Rebecca Bol',
    age: 34,
    dateOfBirth: '1992-03-28',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Nuer (Naath)',
    subTribeOrClan: 'Lou Nuer / Mor',
    nativeLanguage: 'Nuer (Thok Nath)',
    nationality: 'South Sudan',
    community: 'Bentiu Riverside Block',
    subCountyOrBoma: 'Rubkona North Boma',
    countyOrPayam: 'Rubkona County',
    stateOrRegion: 'Unity State',
    residentialAddress: 'Sector 4, Riverside Bend',
    durationOfStayYears: 8,
    householdId: 'HH-002',
    householdRole: 'Spouse',
    isHouseholdHead: false,
    educationLevel: 'Secondary Education',
    isLiterate: true,
    employmentStatus: 'Agriculture & Farming',
    primaryOccupation: 'Fisheries & Horticulture',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Peter Gatwich Koang',
    enumeratorBadgeId: 'ENUM-088',
    enumerationDate: '2026-08-16',
    verificationStatus: 'Verified',
    createdAt: '2026-08-16T10:30:00Z',
    updatedAt: '2026-08-16T10:30:00Z'
  },
  {
    id: 'CEN-2026-0203',
    fullName: 'Koang Gatluak Ruai',
    age: 9,
    dateOfBirth: '2017-08-11',
    gender: 'Male',
    maritalStatus: 'Single',
    tribe: 'Nuer (Naath)',
    subTribeOrClan: 'Lou Nuer / Mor',
    nativeLanguage: 'Nuer (Thok Nath)',
    nationality: 'South Sudan',
    community: 'Bentiu Riverside Block',
    subCountyOrBoma: 'Rubkona North Boma',
    countyOrPayam: 'Rubkona County',
    stateOrRegion: 'Unity State',
    residentialAddress: 'Sector 4, Riverside Bend',
    durationOfStayYears: 8,
    householdId: 'HH-002',
    householdRole: 'Son / Daughter',
    isHouseholdHead: false,
    educationLevel: 'Primary Education',
    isLiterate: true,
    employmentStatus: 'Student',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Peter Gatwich Koang',
    enumeratorBadgeId: 'ENUM-088',
    enumerationDate: '2026-08-16',
    verificationStatus: 'Verified',
    createdAt: '2026-08-16T10:40:00Z',
    updatedAt: '2026-08-16T10:40:00Z'
  },
  {
    id: 'CEN-2026-0301',
    nationalId: 'SS-11894411-K',
    fullName: 'Lado Emmanuel Kenyi',
    age: 52,
    dateOfBirth: '1974-02-18',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Bari',
    subTribeOrClan: 'Bari Pöri',
    nativeLanguage: 'Bari',
    nationality: 'South Sudan',
    community: 'Kator Parish Ward',
    subCountyOrBoma: 'Kator Central Boma',
    countyOrPayam: 'Juba City Council',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Cathedral Way, House 29',
    durationOfStayYears: 30,
    householdId: 'HH-003',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Post-Graduate (Master/PhD)',
    isLiterate: true,
    employmentStatus: 'Employed (Public/Civil Service)',
    primaryOccupation: 'Urban Planning Director',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-17',
    verificationStatus: 'Verified',
    createdAt: '2026-08-17T11:00:00Z',
    updatedAt: '2026-08-17T11:00:00Z'
  },
  {
    id: 'CEN-2026-0302',
    nationalId: 'SS-11894412-L',
    fullName: 'Poni Christine Wani',
    age: 49,
    dateOfBirth: '1977-07-22',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Bari',
    subTribeOrClan: 'Bari Pöri',
    nativeLanguage: 'Bari',
    nationality: 'South Sudan',
    community: 'Kator Parish Ward',
    subCountyOrBoma: 'Kator Central Boma',
    countyOrPayam: 'Juba City Council',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Cathedral Way, House 29',
    durationOfStayYears: 28,
    householdId: 'HH-003',
    householdRole: 'Spouse',
    isHouseholdHead: false,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Private Sector)',
    primaryOccupation: 'Headmistress, St. Kizito Primary',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-17',
    verificationStatus: 'Verified',
    createdAt: '2026-08-17T11:15:00Z',
    updatedAt: '2026-08-17T11:15:00Z'
  },
  {
    id: 'CEN-2026-0401',
    nationalId: 'SS-33019842-M',
    fullName: 'Natanael Bazia Gbudue',
    age: 63,
    dateOfBirth: '1963-05-10',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Azande',
    subTribeOrClan: 'Avongara Dynasty',
    nativeLanguage: 'Zande',
    nationality: 'South Sudan',
    community: 'Yambio Green Valley',
    subCountyOrBoma: 'Gangura Boma',
    countyOrPayam: 'Yambio Payam',
    stateOrRegion: 'Western Equatoria',
    residentialAddress: 'Forestry Lane, Mile 3',
    durationOfStayYears: 45,
    householdId: 'HH-004',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Vocational / Diploma',
    isLiterate: true,
    employmentStatus: 'Agriculture & Farming',
    primaryOccupation: 'Agro-forestry & Coffee Plantation Farmer',
    hasSpecialNeedsOrDisability: true,
    disabilityType: 'Visual impairment (mild low vision)',
    enumeratorName: 'Daniel Justin Tombura',
    enumeratorBadgeId: 'ENUM-105',
    enumerationDate: '2026-08-18',
    verificationStatus: 'Verified',
    createdAt: '2026-08-18T09:10:00Z',
    updatedAt: '2026-08-18T09:10:00Z'
  },
  {
    id: 'CEN-2026-0402',
    nationalId: 'SS-33019843-N',
    fullName: 'Zipporah Nanzala Bakindo',
    age: 58,
    dateOfBirth: '1968-12-05',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Azande',
    subTribeOrClan: 'Amangbondo',
    nativeLanguage: 'Zande',
    nationality: 'South Sudan',
    community: 'Yambio Green Valley',
    subCountyOrBoma: 'Gangura Boma',
    countyOrPayam: 'Yambio Payam',
    stateOrRegion: 'Western Equatoria',
    residentialAddress: 'Forestry Lane, Mile 3',
    durationOfStayYears: 40,
    householdId: 'HH-004',
    householdRole: 'Spouse',
    isHouseholdHead: false,
    educationLevel: 'Primary Education',
    isLiterate: true,
    employmentStatus: 'Artisan / Trade',
    primaryOccupation: 'Traditional Weaving & Basketry',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Daniel Justin Tombura',
    enumeratorBadgeId: 'ENUM-105',
    enumerationDate: '2026-08-18',
    verificationStatus: 'Verified',
    createdAt: '2026-08-18T09:25:00Z',
    updatedAt: '2026-08-18T09:25:00Z'
  },
  {
    id: 'CEN-2026-0501',
    nationalId: 'SS-77123990-P',
    fullName: 'Onyango Oyoo Kwajok',
    age: 31,
    dateOfBirth: '1995-03-12',
    gender: 'Male',
    maritalStatus: 'Single',
    tribe: 'Shilluk (Chollo)',
    subTribeOrClan: 'Kwa Okel',
    nativeLanguage: 'Shilluk (Dhok Chollo)',
    nationality: 'South Sudan',
    community: 'Malakal Central Settlement',
    subCountyOrBoma: 'Pashodo Ward',
    countyOrPayam: 'Malakal County',
    stateOrRegion: 'Upper Nile',
    residentialAddress: 'Nile Port Quarters, Block 2',
    durationOfStayYears: 6,
    householdId: 'HH-005',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Private Sector)',
    primaryOccupation: 'Logistics Supervisor, River Transport',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Sarah Nyawello Othow',
    enumeratorBadgeId: 'ENUM-019',
    enumerationDate: '2026-08-19',
    verificationStatus: 'Verified',
    createdAt: '2026-08-19T14:10:00Z',
    updatedAt: '2026-08-19T14:10:00Z'
  },
  {
    id: 'CEN-2026-0601',
    nationalId: 'SS-55443322-Q',
    fullName: 'Lokong Mark Lopuke',
    age: 27,
    dateOfBirth: '1999-10-04',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Toposa',
    subTribeOrClan: 'Nyangea',
    nativeLanguage: 'Toposa',
    nationality: 'South Sudan',
    community: 'Kapoeta Goldfield Boma',
    subCountyOrBoma: 'Singaita Boma',
    countyOrPayam: 'Kapoeta South',
    stateOrRegion: 'Eastern Equatoria',
    residentialAddress: 'Singaita Riverbank Kraal',
    durationOfStayYears: 27,
    householdId: 'HH-006',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'None / Informal',
    isLiterate: false,
    employmentStatus: 'Pastoralism & Livestock',
    primaryOccupation: 'Cattle Breeder & Pastoral Herd Leader',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Helen Nakiru Longoli',
    enumeratorBadgeId: 'ENUM-067',
    enumerationDate: '2026-08-20',
    verificationStatus: 'Verified',
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z'
  },
  {
    id: 'CEN-2026-0602',
    fullName: 'Nakiru Cecilia Lochoro',
    age: 24,
    dateOfBirth: '2002-04-18',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Toposa',
    subTribeOrClan: 'Nyangea',
    nativeLanguage: 'Toposa',
    nationality: 'South Sudan',
    community: 'Kapoeta Goldfield Boma',
    subCountyOrBoma: 'Singaita Boma',
    countyOrPayam: 'Kapoeta South',
    stateOrRegion: 'Eastern Equatoria',
    residentialAddress: 'Singaita Riverbank Kraal',
    durationOfStayYears: 6,
    householdId: 'HH-006',
    householdRole: 'Spouse',
    isHouseholdHead: false,
    educationLevel: 'None / Informal',
    isLiterate: false,
    employmentStatus: 'Homemaker / Caregiver',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Helen Nakiru Longoli',
    enumeratorBadgeId: 'ENUM-067',
    enumerationDate: '2026-08-20',
    verificationStatus: 'Verified',
    createdAt: '2026-08-20T08:15:00Z',
    updatedAt: '2026-08-20T08:15:00Z'
  },
  {
    id: 'CEN-2026-0701',
    nationalId: 'SS-88992211-R',
    fullName: 'Achiro Sunday Okello',
    age: 36,
    dateOfBirth: '1990-08-14',
    gender: 'Female',
    maritalStatus: 'Widowed',
    tribe: 'Acholi',
    subTribeOrClan: 'Payira',
    nativeLanguage: 'Acholi',
    nationality: 'South Sudan',
    community: 'Nimule Border Township',
    subCountyOrBoma: 'Customs Zone B',
    countyOrPayam: 'Magwi County',
    stateOrRegion: 'Eastern Equatoria',
    residentialAddress: 'Kaya Road, Near Market Square',
    durationOfStayYears: 11,
    householdId: 'HH-007',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Secondary Education',
    isLiterate: true,
    employmentStatus: 'Self-Employed / Business',
    primaryOccupation: 'Cross-border Produce Trader',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'John Bosco Loro',
    enumeratorBadgeId: 'ENUM-033',
    enumerationDate: '2026-08-21',
    verificationStatus: 'Verified',
    createdAt: '2026-08-21T13:40:00Z',
    updatedAt: '2026-08-21T13:40:00Z'
  },
  {
    id: 'CEN-2026-0801',
    nationalId: 'SS-66778899-S',
    fullName: 'Lodu Samuel Wani',
    age: 29,
    dateOfBirth: '1997-01-25',
    gender: 'Male',
    maritalStatus: 'Single',
    tribe: 'Mundari',
    subTribeOrClan: 'Tali Clan',
    nativeLanguage: 'Bari',
    nationality: 'South Sudan',
    community: 'Gudele Community',
    subCountyOrBoma: 'Block 7 Gudele',
    countyOrPayam: 'Juba Payam',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Gudele Roundabout, Lane 4',
    durationOfStayYears: 5,
    householdId: 'HH-008',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Private Sector)',
    primaryOccupation: 'Software & Telecommunications Engineer',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-22',
    verificationStatus: 'Verified',
    createdAt: '2026-08-22T16:00:00Z',
    updatedAt: '2026-08-22T16:00:00Z'
  },
  {
    id: 'CEN-2026-0901',
    nationalId: 'SS-22334455-T',
    fullName: 'Adek Veronica Chol',
    age: 72,
    dateOfBirth: '1954-06-19',
    gender: 'Female',
    maritalStatus: 'Widowed',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Bor / Gok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Bor Town Zone 3',
    subCountyOrBoma: 'Arek Boma',
    countyOrPayam: 'Bor South County',
    stateOrRegion: 'Jonglei',
    residentialAddress: 'Nile Crescent, Compound 18',
    durationOfStayYears: 50,
    householdId: 'HH-009',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'None / Informal',
    isLiterate: false,
    employmentStatus: 'Retired / Pensioner',
    primaryOccupation: 'Community Elder & Matriarch',
    hasSpecialNeedsOrDisability: true,
    disabilityType: 'Mobility impairment (uses walking cane)',
    enumeratorName: 'David Mabior Garang',
    enumeratorBadgeId: 'ENUM-012',
    enumerationDate: '2026-08-23',
    verificationStatus: 'Verified',
    createdAt: '2026-08-23T11:20:00Z',
    updatedAt: '2026-08-23T11:20:00Z'
  },
  {
    id: 'CEN-2026-1001',
    nationalId: 'SS-99112233-U',
    fullName: 'James Wol Machok',
    age: 35,
    dateOfBirth: '1991-04-16',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Luac / Gok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Rumbek Palm Grove',
    subCountyOrBoma: 'Rumbek Central Boma',
    countyOrPayam: 'Rumbek Central',
    stateOrRegion: 'Lakes State',
    residentialAddress: 'Freedom Square Avenue, No. 12',
    durationOfStayYears: 12,
    householdId: 'HH-010',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Public/Civil Service)',
    primaryOccupation: 'Data Systems & Statistician Officer',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Gabriel Mabor Dut',
    enumeratorBadgeId: 'ENUM-055',
    enumerationDate: '2026-08-24',
    verificationStatus: 'Verified',
    createdAt: '2026-08-24T09:00:00Z',
    updatedAt: '2026-08-24T09:00:00Z'
  },
  {
    id: 'CEN-2026-1002',
    fullName: 'Yar Elizabeth Deng',
    age: 30,
    dateOfBirth: '1996-08-11',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Agar / Rup',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Rumbek Palm Grove',
    subCountyOrBoma: 'Rumbek Central Boma',
    countyOrPayam: 'Rumbek Central',
    stateOrRegion: 'Lakes State',
    residentialAddress: 'Freedom Square Avenue, No. 12',
    durationOfStayYears: 8,
    householdId: 'HH-010',
    householdRole: 'Spouse',
    isHouseholdHead: false,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Employed (Private Sector)',
    primaryOccupation: 'Registered Midwife & Nurse',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Gabriel Mabor Dut',
    enumeratorBadgeId: 'ENUM-055',
    enumerationDate: '2026-08-24',
    verificationStatus: 'Verified',
    createdAt: '2026-08-24T09:15:00Z',
    updatedAt: '2026-08-24T09:15:00Z'
  },
  {
    id: 'CEN-2026-1003',
    fullName: 'Machok James Wol',
    age: 5,
    dateOfBirth: '2021-02-10',
    gender: 'Male',
    maritalStatus: 'Single',
    tribe: 'Dinka (Jieng)',
    subTribeOrClan: 'Luac / Gok',
    nativeLanguage: 'Dinka (Thuɔŋjäŋ)',
    nationality: 'South Sudan',
    community: 'Rumbek Palm Grove',
    subCountyOrBoma: 'Rumbek Central Boma',
    countyOrPayam: 'Rumbek Central',
    stateOrRegion: 'Lakes State',
    residentialAddress: 'Freedom Square Avenue, No. 12',
    durationOfStayYears: 5,
    householdId: 'HH-010',
    householdRole: 'Son / Daughter',
    isHouseholdHead: false,
    educationLevel: 'Primary Education',
    isLiterate: true,
    employmentStatus: 'Student',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Gabriel Mabor Dut',
    enumeratorBadgeId: 'ENUM-055',
    enumerationDate: '2026-08-24',
    verificationStatus: 'Verified',
    createdAt: '2026-08-24T09:30:00Z',
    updatedAt: '2026-08-24T09:30:00Z'
  },
  {
    id: 'CEN-2026-1101',
    nationalId: 'SS-11223344-V',
    fullName: 'Kiden Joyce Wani',
    age: 23,
    dateOfBirth: '2003-05-19',
    gender: 'Female',
    maritalStatus: 'Single',
    tribe: 'Kuku',
    subTribeOrClan: 'Kuku Kajo-Keji',
    nativeLanguage: 'Bari',
    nationality: 'South Sudan',
    community: 'Juba Na Bari Sector',
    subCountyOrBoma: 'Na Bari Ward 4',
    countyOrPayam: 'Juba City Council',
    stateOrRegion: 'Central Equatoria',
    residentialAddress: 'Airport Link Road, Flat 5',
    durationOfStayYears: 3,
    householdId: 'HH-011',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Tertiary / Bachelor Degree',
    isLiterate: true,
    employmentStatus: 'Student',
    primaryOccupation: 'Medical Laboratory Student',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Grace Kiden Taban',
    enumeratorBadgeId: 'ENUM-042',
    enumerationDate: '2026-08-25',
    verificationStatus: 'Verified',
    createdAt: '2026-08-25T15:20:00Z',
    updatedAt: '2026-08-25T15:20:00Z'
  },
  {
    id: 'CEN-2026-1201',
    nationalId: 'SS-77665544-W',
    fullName: 'Othow Simon Kwajok',
    age: 56,
    dateOfBirth: '1970-11-08',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Shilluk (Chollo)',
    subTribeOrClan: 'Pashodo Royal Clan',
    nativeLanguage: 'Shilluk (Dhok Chollo)',
    nationality: 'South Sudan',
    community: 'Malakal Central Settlement',
    subCountyOrBoma: 'Pashodo Ward',
    countyOrPayam: 'Malakal County',
    stateOrRegion: 'Upper Nile',
    residentialAddress: 'Market Quarter, Compound 4',
    durationOfStayYears: 22,
    householdId: 'HH-012',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Secondary Education',
    isLiterate: true,
    employmentStatus: 'Self-Employed / Business',
    primaryOccupation: 'Canoe & Engine Mechanic',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Sarah Nyawello Othow',
    enumeratorBadgeId: 'ENUM-019',
    enumerationDate: '2026-08-26',
    verificationStatus: 'Verified',
    createdAt: '2026-08-26T10:10:00Z',
    updatedAt: '2026-08-26T10:10:00Z'
  },
  {
    id: 'CEN-2026-1301',
    nationalId: 'SS-88776655-X',
    fullName: 'Akello Sharon Odong',
    age: 28,
    dateOfBirth: '1998-09-03',
    gender: 'Female',
    maritalStatus: 'Single',
    tribe: 'Madi',
    subTribeOrClan: 'Oyuwi Madi',
    nativeLanguage: 'Madi',
    nationality: 'South Sudan',
    community: 'Nimule Border Township',
    subCountyOrBoma: 'Panyikwara Boma',
    countyOrPayam: 'Magwi County',
    stateOrRegion: 'Eastern Equatoria',
    residentialAddress: 'Hospital Road, House 8',
    durationOfStayYears: 7,
    householdId: 'HH-013',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Vocational / Diploma',
    isLiterate: true,
    employmentStatus: 'Employed (Private Sector)',
    primaryOccupation: 'Pharmacist Assistant',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'John Bosco Loro',
    enumeratorBadgeId: 'ENUM-033',
    enumerationDate: '2026-08-27',
    verificationStatus: 'Verified',
    createdAt: '2026-08-27T16:45:00Z',
    updatedAt: '2026-08-27T16:45:00Z'
  },
  {
    id: 'CEN-2026-1401',
    nationalId: 'SS-55667788-Y',
    fullName: 'Lopeta Peter Lotuko',
    age: 41,
    dateOfBirth: '1985-03-29',
    gender: 'Male',
    maritalStatus: 'Married',
    tribe: 'Lotuko (Otuho)',
    subTribeOrClan: 'Lofit Hilly',
    nativeLanguage: 'Lotuko',
    nationality: 'South Sudan',
    community: 'Torit Hillside Community',
    subCountyOrBoma: 'Hiyala Boma',
    countyOrPayam: 'Torit County',
    stateOrRegion: 'Eastern Equatoria',
    residentialAddress: 'Hill View Street, Compound 6',
    durationOfStayYears: 18,
    householdId: 'HH-014',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Secondary Education',
    isLiterate: true,
    employmentStatus: 'Agriculture & Farming',
    primaryOccupation: 'Sorghum & Sesame Cooperative Lead',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Helen Nakiru Longoli',
    enumeratorBadgeId: 'ENUM-067',
    enumerationDate: '2026-08-28',
    verificationStatus: 'Verified',
    createdAt: '2026-08-28T11:00:00Z',
    updatedAt: '2026-08-28T11:00:00Z'
  },
  {
    id: 'CEN-2026-1501',
    nationalId: 'SS-33445566-Z',
    fullName: 'Fatima Al-Nur Hassan',
    age: 38,
    dateOfBirth: '1988-07-14',
    gender: 'Female',
    maritalStatus: 'Married',
    tribe: 'Fertit',
    subTribeOrClan: 'Balanda Bviri',
    nativeLanguage: 'Arabic (Juba Arabic)',
    nationality: 'South Sudan',
    community: 'Wau Old Town',
    subCountyOrBoma: 'Kator Wau Boma',
    countyOrPayam: 'Wau County',
    stateOrRegion: 'Western Bahr el Ghazal',
    residentialAddress: 'Old Catholic Mission Road',
    durationOfStayYears: 25,
    householdId: 'HH-015',
    householdRole: 'Head of Household',
    isHouseholdHead: true,
    educationLevel: 'Vocational / Diploma',
    isLiterate: true,
    employmentStatus: 'Self-Employed / Business',
    primaryOccupation: 'Textile Tailor & Fashion Designer',
    hasSpecialNeedsOrDisability: false,
    enumeratorName: 'Mario Taban Udo',
    enumeratorBadgeId: 'ENUM-094',
    enumerationDate: '2026-08-29',
    verificationStatus: 'Verified',
    createdAt: '2026-08-29T14:30:00Z',
    updatedAt: '2026-08-29T14:30:00Z'
  }
];
